resources:
- name: compute.v1.instance0
  properties:
    disks:
    - boot: true
      deviceName: boot
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-9
      type: PERSISTENT
    machineType: f1-micro
    networkInterfaces:
    - network: global/networks/default
    zone: us-east-1a
  type: compute.v1.instance
